### ISSUE TITLE
Get Status with Completion Data - Unable to verify OTP code

### ISSUE THREAD

**Issue by ParraAlvaro** [TeleSign/ruby_telesign_enterprise#2]
After sending a `Verify SMS` without specifying the OTP, so that TeleSign generates the OTP code, I tried to verify an OTP code.

Following the docs in: [Get Status with Completion Data](https://enterprise.telesign.com/api-reference/apis/get-status-verify-transaction-api/get-status-with-completion-data#get-status-with-completion-data)

As in the example in: [Get Status Completion Data Example](https://enterprise.telesign.com/api-reference/apis/get-status-verify-transaction-api/get-status-with-completion-data#get-status-completion-data-example)
```ruby
reference_id = 'AEBC93B5898342F790E4E19FED41A7DA'
verify_code = '57244'
response = @telesign_verify_client.status(reference_id, verify_code: verify_code)
```

The API client did not send the `verify_code` with the GET request. So the API handles the request as a normal [Get Transaction Status](https://enterprise.telesign.com/api-reference/apis/get-status-verify-transaction-api/get-transaction-status#get-transaction-status).

`"verify": {"code_state": "UNKNOWN", "code_entered": null}`

**Comment by ramsay** [comment]
Thank you for reporting this bug. It had existed since the initial release of the 2.X verison of the telesign ruby sdk. The 2.2.3 version of the SDK has the fix for the bug and the dependency version has been updated in the enterprise sdk.
